name: pdflatex
author: Marcin Białoń <marcin@bialon.net>
description: pdflatex action
inputs:
  path:
    description: 'source path'
    required: true
runs:
  using: 'docker'
  image: 'docker://mbialon/texlive:latest'
  args: ['${{inputs.path}}']
