name: main
on:
  push:
    branches:
      - master
env:
  IMAGE: mbialon/texlive:latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t $IMAGE .
      - run: docker push $IMAGE
